// Code generated by inject-logger; DO NOT EDIT.
// safe guard magic: 9ed0de76-4d48-4068-b392-a152cd6d3ab1

package deep_init

//go:generate go run ../../../cmd/inject-logger --prefix="gongt"

import (
	"github.com/gongt/go/pkg/logger"
)

const _dbg_tag = "gongt:tools:reflection:deep_init"

func debug(msg string) {
	logger.DLog(_dbg_tag, msg)
}

var _ = debug

func debugf(fmt string, args ...any) {
	logger.DLogF(_dbg_tag, fmt, args...)
}

var _ = debugf

func print(fmt string) {
	logger.Log(_dbg_tag, fmt)
}

var _ = print

func printf(fmt string, args ...any) {
	logger.LogF(_dbg_tag, fmt, args...)
}

var _ = printf
