// Code generated by "stringer -type=ValueType -output=value_kind_generate.go"; DO NOT EDIT.

package kinds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeIdUnknown-0]
	_ = x[TypeIdBytes-1]
	_ = x[TypeIdString-2]
	_ = x[TypeIdUint-3]
	_ = x[TypeIdUint64-4]
	_ = x[TypeIdUint32-5]
	_ = x[TypeIdUint16-6]
	_ = x[TypeIdUint8-7]
	_ = x[TypeIdInt-8]
	_ = x[TypeIdInt64-9]
	_ = x[TypeIdInt32-10]
	_ = x[TypeIdInt16-11]
	_ = x[TypeIdInt8-12]
	_ = x[TypeIdByte-13]
	_ = x[TypeIdBool-14]
	_ = x[TypeIdFloat64-15]
	_ = x[TypeIdFloat32-16]
	_ = x[TypeIdComplex128-17]
	_ = x[TypeIdComplex64-18]
	_ = x[TypeIdJson-19]
	_ = x[TypeIdFunc-20]
	_ = x[TypeIdChannel-21]
	_ = x[TypeIdStruct-22]
	_ = x[TypeIdArray-23]
	_ = x[TypeIdMap-24]
}

const _ValueType_name = "TypeIdUnknownTypeIdBytesTypeIdStringTypeIdUintTypeIdUint64TypeIdUint32TypeIdUint16TypeIdUint8TypeIdIntTypeIdInt64TypeIdInt32TypeIdInt16TypeIdInt8TypeIdByteTypeIdBoolTypeIdFloat64TypeIdFloat32TypeIdComplex128TypeIdComplex64TypeIdJsonTypeIdFuncTypeIdChannelTypeIdStructTypeIdArrayTypeIdMap"

var _ValueType_index = [...]uint16{0, 13, 24, 36, 46, 58, 70, 82, 93, 102, 113, 124, 135, 145, 155, 165, 178, 191, 207, 222, 232, 242, 255, 267, 278, 287}

func (i ValueType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ValueType_index)-1 {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[idx]:_ValueType_index[idx+1]]
}
