// Code generated by "github.com/gongt/go/cmd/exports" DO NOT EDIT.
// safe guard magic: 33084b74-3121-47cd-9093-db68da5893bc

//go:generate go run github.com/gongt/go/cmd/exports

package errors

import (
	udzBalWrrTt "iter"

	iJQdTeodqqt "github.com/gongt/go/pkg/errors/internal"
	bJdHFZXnetMM "github.com/gongt/go/pkg/errors/internal/iterator"
)

type StackTrace = iJQdTeodqqt.StackTrace
type UnJoin = iJQdTeodqqt.UnJoin

func IsJoined(arg1 error) bool {
	return iJQdTeodqqt.IsJoined(arg1)
}

type UnWrap = iJQdTeodqqt.UnWrap
type Detailer = iJQdTeodqqt.Detailer
type MessageOverrider = iJQdTeodqqt.MessageOverrider
type DetailerWriter = iJQdTeodqqt.DetailerWriter
type AlsoBe = iJQdTeodqqt.AlsoBe

// [底层操作] 循环遍历一个错误的Wrap()链
//   - 遇到Join()时: 继续递归它的第一个错误
func IterWrapChain(arg1 error) udzBalWrrTt.Seq[error] {
	return bJdHFZXnetMM.IterWrapChain(arg1)
}

// [底层操作] 循环遍历一个错误的reason链
func IterReasonChain(arg1 error) udzBalWrrTt.Seq[error] {
	return bJdHFZXnetMM.IterReasonChain(arg1)
}

// [底层操作] 循环遍历一个错误的Wrap()、Join()链，
//   - 第二个yield值为Join()层级
func IterWrapTree(arg1 error) udzBalWrrTt.Seq2[error, uint] {
	return bJdHFZXnetMM.IterWrapTree(arg1)
}

// [底层操作] 遍历 Wrap()、Join() 链，并在发现附加数据时yield
func IterEveryDetail(arg1 error) udzBalWrrTt.Seq[map[string]any] {
	return bJdHFZXnetMM.IterEveryDetail(arg1)
}
