package codegen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"os"

	"github.com/gongt/go/pkg/errors"
	"github.com/gongt/go/pkg/fsys/fpath"
	sourcecode "github.com/gongt/go/pkg/source_code"
	"github.com/jessevdk/go-flags"
)

type GeneratorEnvironment struct {
	InputFile string `long:"input" description:"Path to the input file" env:"GOFILE"`
	Cwd       string
	Args      []string
	Title     string
	Magic     string
	goMod     *sourcecode.GoModFile
}

func CreateEnvironment(title string, magic string) (*GeneratorEnvironment, error) {
	var ret = &GeneratorEnvironment{
		Title: title,
		Magic: magic,
	}

	cwd, err := os.Getwd()
	if err != nil {
		return nil, errors.Extend(err, "无法获取当前工作目录")
	}
	ret.Cwd = cwd

	args, err := flags.NewParser(ret, flags.IgnoreUnknown).Parse()
	if err != nil {
		return nil, errors.Extend(err, "无法解析命令行参数")
	}

	ret.Args = args

	if ret.InputFile == "" {
		return nil, errors.NewAnonymous("必须提供输入文件路径")
	}

	f := fpath.New(ret.Cwd).Join(ret.InputFile)
	err = f.RealpathExisting()
	if err != nil {
		return nil, err
	}

	ret.InputFile = f.Raw()
	if stat, err := os.Stat(ret.InputFile); err != nil || stat.IsDir() {
		if os.IsNotExist(err) {
			// 允许不存在
		} else {
			return nil, errors.NewAnonymous("输入文件路径无效").WithDetails("path", ret.InputFile)
		}
	}

	return ret, nil
}

func (env *GeneratorEnvironment) ReadAsString() (string, error) {
	data, err := os.ReadFile(env.InputFile)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", errors.Extend(err, "无法读取输入文件").WithDetails("path", env.InputFile)
	}
	return string(data), nil
}

func (env *GeneratorEnvironment) ParseInput() (*ast.File, error) {
	return env.ParseInputMode(parser.ParseComments)
}

func (env *GeneratorEnvironment) ParseInputMode(mode parser.Mode) (*ast.File, error) {
	return sourcecode.ReadSourceFile(env.InputFile, mode)
}

func (env *GeneratorEnvironment) ParseArgs(output any) error {
	args, err := flags.NewParser(output, flags.IgnoreUnknown).ParseArgs(env.Args)
	if err != nil {
		return errors.Extend(err, "无法解析命令行参数")
	}
	env.Args = args
	return nil
}

func (env *GeneratorEnvironment) NewOutput(relpath string, prefix string) (*GoFileWriter, error) {
	f := fpath.New(env.Cwd).Join(relpath)
	if err := f.RealpathExisting(); err != nil {
		return nil, err
	}

	r := NewGoFile(f.Raw(), env.Magic)
	r.Heading(prefix)
	r.Heading(env.DoNotModify())

	if _, err := r.Prepare(); err != nil {
		return nil, errors.Extend(err, "无法准备输出文件").WithDetails("path", r.Path)
	}

	return r, nil
}

func (env *GeneratorEnvironment) DoNotModify() string {
	return fmt.Sprint(`// Code generated by `, env.Title, `; DO NOT EDIT.`, "\n")
}

func (env *GeneratorEnvironment) FindGoMod() (*sourcecode.GoModFile, error) {
	if env.goMod != nil {
		return env.goMod, nil
	}
	modFile, err := sourcecode.FindGoMod(env.Cwd)
	if err != nil {
		return nil, err
	}
	env.goMod = modFile
	return modFile, nil
}
