package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path"
	"strings"

	"github.com/gongt/go/pkg/errors"
	sourcecode "github.com/gongt/go/pkg/source_code"
	"github.com/gongt/go/pkg/terminal"
)

type GoFileWriter struct {
	sb *bytes.Buffer

	Path  string
	magic []byte

	prepared    bool
	PackageName string
	Mkdir       bool
}

func NewGoFile(path string, magic string) *GoFileWriter {
	builder := &bytes.Buffer{}

	return &GoFileWriter{
		Path:  path,
		sb:    builder,
		magic: []byte(magic),
		Mkdir: false,
	}
}

func (w *GoFileWriter) Heading(str string) {
	if w.prepared {
		panic("Heading must be called before Prepare()")
	}
	w.sb.WriteString(str)
}

func (w *GoFileWriter) Output() *bytes.Buffer {
	if !w.prepared {
		panic("Prepare() must be called before Output()")
	}
	return w.sb
}

func (w *GoFileWriter) Prepare() (*bytes.Buffer, error) {
	if w.prepared {
		return w.sb, nil
	}

	dir := path.Dir(w.Path)
	if w.Mkdir {
		if _, err := os.Stat(dir); err != nil {
			if os.IsNotExist(err) {
				if w.PackageName == "" {
					w.PackageName = path.Base(dir)
				}
				if err := os.MkdirAll(dir, 0755); err != nil {
					return nil, errors.Extend(err, "无法创建目录").WithDetails("path", dir)
				}
			} else {
				return nil, errors.Extend(err, "无法访问目录").WithDetails("path", dir)
			}
		}
		w.Mkdir = false
	}

	w.prepared = true

	if w.PackageName == "" {
		name, err := sourcecode.DetectPackageName(dir)
		if err != nil {
			return nil, errors.Extend(err, "检测包名失败")
		}
		w.PackageName = name
	}

	sb := w.sb
	sb.WriteString("// safe guard magic: ")
	sb.Write(w.magic)
	sb.WriteString("\n\npackage ")
	sb.WriteString(w.PackageName)
	sb.WriteString("\n\n")

	return w.sb, nil
}

func (w *GoFileWriter) WriteFile() error {
	w.safeGuard()
	return w.ForceOverride()
}

func (w *GoFileWriter) ForceOverride() error {
	if !w.prepared {
		panic("Prepare() must be called before ForceOverride()/WriteFile()")
	}

	bytes := w.sb.Bytes()
	formated, err := format.Source(bytes)
	if err != nil {
		return errors.Extend(err, "无法格式化代码").WithDetails("source", string(bytes))
	}
	if err := os.WriteFile(w.Path, formated, 0644); err != nil {
		return errors.Extend(err, "无法写入文件").WithDetails("path", w.Path)
	}

	log.Println("写入文件: ", w.Path)

	return nil
}

func (w *GoFileWriter) safeGuard() {
	content, err := os.ReadFile(w.Path)
	if err != nil {
		if os.IsNotExist(err) {
			return
		}
		panic(err)
	}

	if bytes.Contains(content, w.magic) {
		return
	}

	found_unexpected_content := false
	for _, line := range bytes.Split(content, []byte("\n")) {
		if len(line) == 0 || bytes.HasPrefix(line, []byte("//")) || bytes.HasPrefix(line, []byte("package ")) {
			continue
		}

		found_unexpected_content = true
		log.Printf("发现未被工具生成的内容: %s\n", line)
		break
	}

	if !found_unexpected_content {
		return
	}

	if terminal.HasTTY() {
		w.ask()
	} else {
		panic(fmt.Sprintf(`  The %s file is not empty and was not generated by this tool.
  You must delete the contents of the file before running this tool again.`, w.Path))
	}
}

func (w *GoFileWriter) ask() {
	fmt.Printf("  The %s file already exists and was not generated by this tool.", w.Path)
	fmt.Println("  If you continue, the file will be overwritten and any changes will be lost.")
	fmt.Print("  Do you want to continue? (y/n): ")

	var response string

	f, err := terminal.OpenTTY()
	if err != nil {
		panic(err)
	}
	_, err = fmt.Fscanln(f, &response)
	if err != nil {
		response = "n"
	}

	rsp := strings.ToLower(response)
	if rsp != "y" && rsp != "yes" {
		fmt.Print("Aborting...\n\n")
		os.Exit(1)
	}
}
