package main

import (
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/gongt/go/cmd/exports/internal"
	"github.com/gongt/go/pkg/filesys"
	"github.com/gongt/go/pkg/terminal"
)

const MAGIC_STRING = "33084b74-3121-47cd-9093-db68da5893bc"

func main() {
	var wd string
	var err error

	if wd, err = os.Getwd(); err != nil {
		panic(err)
	}

	goFile := os.Getenv("GOFILE")
	if goFile == "" {
		if len(os.Args) <= 1 {
			panic("Must provide a go package directory as the first argument")
		} else if len(os.Args) > 2 {
			panic("Must provide only one argument")
		}
		wd = filesys.MustResolvePath(wd, os.Args[1])

		if stat, err := os.Stat(wd); err != nil || !stat.IsDir() {
			panic(fmt.Sprintf("The provided folder %s is not a valid directory", wd))
		}
	} else {
		if path.Base(goFile) != "exports.go" {
			panic("This generator is only supported inside exports.go")
		}
		goFileAbs := filesys.MustResolvePath(wd, goFile)

		wd = path.Dir(goFileAbs)
	}

	execute(wd)
}

func execute(root string) {
	exportsFile := filesys.MustResolvePath(root, "exports.go")
	internalDir := filesys.MustResolvePath(root, "internal")

	if stat, err := os.Stat(internalDir); err != nil || !stat.IsDir() {
		panic(fmt.Sprintf("The provided folder %s does not contain an internal directory", root))
	}

	safeGuard(exportsFile)

	sb := strings.Builder{}

	for file := range internal.WalkFilesIn(internalDir) {
		internal.ParseFile(&sb, &file)
	}

}

func safeGuard(exportsFile string) {
	content, err := os.ReadFile(exportsFile)
	if err != nil {
		if os.IsNotExist(err) {
			return
		}
		panic(err)
	}

	if strings.Contains(string(content), MAGIC_STRING) {
		return
	}

	for _, line := range strings.Split(string(content), "\n") {
		if line == "" || strings.HasPrefix(line, "//") || strings.HasPrefix(line, "package ") {
			continue
		}
	}

	if terminal.HasTTY() {
		ask()
	} else {
		panic(`  The exports.go file is not empty and was not generated by this tool.
  You must delete the contents of the file before running this tool again.`)
	}
}

func ask() {
	fmt.Println("  The exports.go file already exists and was not generated by this tool.")
	fmt.Println("  If you continue, the file will be overwritten and any changes will be lost.")
	fmt.Print("  Do you want to continue? (y/n): ")

	var response string

	f, err := terminal.OpenTTY()
	if err != nil {
		panic(err)
	}
	_, err = fmt.Fscanln(f, &response)
	if err != nil {
		response = "n"
	}

	rsp := strings.ToLower(response)
	if rsp != "y" && rsp != "yes" {
		fmt.Println("Aborting...\n")
		os.Exit(1)
	}
}
