// Code generated by "github.com/gongt/go/cmd/exports" DO NOT EDIT.
// safe guard magic: 33084b74-3121-47cd-9093-db68da5893bc

//go:generate go run github.com/gongt/go/cmd/exports

package binaries

import (
	"io"

	"github.com/gongt/go/pkg/binaries/internal/endian"
	"github.com/gongt/go/pkg/binaries/internal/packer"
	"github.com/gongt/go/pkg/binaries/internal/streaming"
	"github.com/gongt/go/pkg/interfaces"
)

// - ./pkg/binaries/internal/endian/endian.go

// LittleEndian 包装[binary.LittleEndian]添加了各种类型的函数
var LittleEndian = endian.LittleEndian

// BigEndian 包装[binary.BigEndian]添加了各种类型的函数
var BigEndian = endian.BigEndian

// NativeEndian 包装本地字节序添加了各种类型的函数
var NativeEndian = endian.NativeEndian

// - ./pkg/binaries/internal/endian/endian_basic.go

// No exported symbols

// - ./pkg/binaries/internal/endian/endian_inherit.go

// No exported symbols

// - ./pkg/binaries/internal/packer/pack.go

type Packer = packer.Packer

// NewPack 创建一个新的packer实例
func NewPack[T io.Writer](arg1 T, arg2 endian.ByteOrder) packer.Packer {
	return packer.NewPack(arg1, arg2)
}

func NewPackEndian[T io.Writer](arg1 T, arg2 endian.ByteOrder) packer.Packer {
	return packer.NewPackEndian(arg1, arg2)
}

// - ./pkg/binaries/internal/packer/pack_buffer.go

// No exported symbols

// - ./pkg/binaries/internal/packer/pack_writer.go

// No exported symbols

// - ./pkg/binaries/internal/packer/unpack.go

type Unpacker = packer.Unpacker

// NewUnpack 创建一个新的unpacker实例，不应再使用data的原始引用，尤其是不能修改data的内容
func NewUnpack(arg1 endian.ByteOrder, arg2 []byte) packer.Unpacker {
	return packer.NewUnpack(arg1, arg2)
}

// - ./pkg/binaries/internal/streaming/chunked_reader.go

type ChunkReader = streaming.ChunkReader

// NewChunkReader 创建一个新的chunkReader实例，sep为数据块的分隔符
func NewChunkReader[T interfaces.ByteSeq](arg1 T) streaming.ChunkReader {
	return streaming.NewChunkReader(arg1)
}

// - ./pkg/binaries/internal/streaming/shared.go

var ErrInsufficientBuffer = streaming.ErrInsufficientBuffer

// - ./pkg/binaries/internal/streaming/stream_buffer.go

type StreamBuffer = streaming.StreamBuffer

func NewStreamBuffer() streaming.StreamBuffer {
	return streaming.NewStreamBuffer()
}

// - ./pkg/binaries/internal/struct_stream/struct_stream.go

// No exported symbols

// - ./pkg/binaries/internal/struct_stream/struct_stream_read.go

// No exported symbols

// - ./pkg/binaries/internal/struct_stream/struct_stream_write.go

// No exported symbols
