// Code generated by "github.com/gongt/go/cmd/exports" DO NOT EDIT.
// safe guard magic: 33084b74-3121-47cd-9093-db68da5893bc

//go:generate go run github.com/gongt/go/cmd/exports

package binaries

import (
	pkg2 "encoding/binary"
	pkg1 "io"

	pkg0 "github.com/gongt/go/pkg/binaries/internal/packer"
	pkg3 "github.com/gongt/go/pkg/binaries/internal/streaming"
	pkg4 "github.com/gongt/go/pkg/interfaces"
)

// - ./pkg/binaries/internal/packer/pack.go

type Packer = pkg0.Packer

// NewPack 创建一个新的packer实例
func NewPack(arg1 pkg1.Writer, arg2 pkg2.ByteOrder) pkg0.Packer {
	return pkg0.NewPack(arg1, arg2)
}

// - ./pkg/binaries/internal/packer/unpack.go

type Unpacker = pkg0.Unpacker

// NewUnpack 创建一个新的unpacker实例，不应再使用data的原始引用
func NewUnpack(arg1 pkg2.ByteOrder, arg2 []byte) pkg0.Unpacker {
	return pkg0.NewUnpack(arg1, arg2)
}

// - ./pkg/binaries/internal/streaming/chunked_reader.go

type ChunkReader = pkg3.ChunkReader

// NewChunkReader 创建一个新的chunkReader实例，sep为数据块的分隔符
func NewChunkReader[T pkg4.ByteSeq](arg1 T) pkg3.ChunkReader {
	return pkg3.NewChunkReader(arg1)
}

// - ./pkg/binaries/internal/streaming/shared.go

var ErrInsufficientBuffer = pkg3.ErrInsufficientBuffer

// - ./pkg/binaries/internal/streaming/stream_buffer.go

type StreamBuffer = pkg3.StreamBuffer

func NewStreamBuffer() pkg3.StreamBuffer {
	return pkg3.NewStreamBuffer()
}

// - ./pkg/binaries/internal/struct_stream/struct_stream_read.go
