// Code generated by "github.com/gongt/go/cmd/exports" DO NOT EDIT.
// safe guard magic: 33084b74-3121-47cd-9093-db68da5893bc

//go:generate go run github.com/gongt/go/cmd/exports

package types

import (
	cdQnIBqUXCFY "github.com/gongt/go/pkg/types/internal/collection"
	bDZGGWjLvIrw "github.com/gongt/go/pkg/types/internal/config_loader"
	bHWoyPpYVbah "github.com/gongt/go/pkg/types/internal/sets"
)

// Collection 任意类型指针的可重复的集合
type Collection[T comparable] = cdQnIBqUXCFY.Collection[T]
type RemoveFunc = cdQnIBqUXCFY.RemoveFunc

// SharedCollection 线程安全的 [Collection]
type SharedCollection[T comparable] = cdQnIBqUXCFY.SharedCollection[T]

// Regexp 是一个包装了 regexp.Regexp 的结构体，用于从配置文件中读取
type Regexp = bDZGGWjLvIrw.Regexp

// Set 集合的数组简易实现，适合只有几个元素的情况
type Set[T comparable] = bHWoyPpYVbah.Set[T]

// SharedSet 线程安全的 [Set]
type SharedSet[T comparable] = bHWoyPpYVbah.SharedSet[T]
