package internal

import "fmt"

type CodegenEnvironmentInterface interface {
	DoNotModify() string
}

var CurrentGenerator CodegenEnvironmentInterface

func CreateSafeGuardComment(magic []byte, who_am_i string) string {
	return fmt.Sprintf(`// Code generated by "%s" DO NOT EDIT.
// safe guard magic: %s


`, who_am_i, magic)
}
