// Code generated by "github.com/gongt/go/cmd/inject-logger" DO NOT EDIT.
// safe guard magic: 9ed0de76-4d48-4068-b392-a152cd6d3ab1

//go:generate go run github.com/gongt/go/cmd/inject-logger --prefix="gongt"

package reflection

import (
	PqpLsWuoVY "github.com/gongt/go/pkg/logger"
)

const _dbg_tag = "gongt:tools:reflection"

func debug(msg string) {
	PqpLsWuoVY.DLog(_dbg_tag, msg)
}

var _ = debug

func debugf(fmt string, args ...any) {
	PqpLsWuoVY.DLogF(_dbg_tag, fmt, args...)
}

var _ = debugf

func print(fmt string) {
	PqpLsWuoVY.Log(_dbg_tag, fmt)
}

var _ = print

func printf(fmt string, args ...any) {
	PqpLsWuoVY.LogF(_dbg_tag, fmt, args...)
}

var _ = printf
